version: 0.2
env:
    git-credential-helper: yes
phases:
  install:
    commands:
        - yum install python3 -y
        - curl -O https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip.py --user
        - pip3 install trufflehog
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Testing Trufflehog in the pre_build phase...
      - trufflehog --regex --entropy=False --max_depth=1 https://git-codecommit.us-east-2.amazonaws.com/v1/repos/test
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: devsecops-$(date +%Y-%m-%d)